"""Generate the synthetic sample referral documents in this folder.

Regenerate with:

    python3 -m venv .venv && .venv/bin/pip install reportlab pillow
    .venv/bin/python samples/generate_samples.py

Every document produced here is entirely synthetic: no real patient,
provider, or organization is represented. Filenames follow the
`synthetic-<description>.<ext>` convention required by
`api/referral/guardrails.py` so they can be uploaded to the running API
as-is (with the `X-Data-Classification: synthetic` header).
"""

from __future__ import annotations

from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from PIL import Image, ImageDraw, ImageFont

OUT_DIR = Path(__file__).parent
BANNER_TEXT = "SYNTHETIC TEST DATA \u2014 NOT REAL PHI \u2014 GENERATED FOR WORKSHOP USE ONLY"

PATIENT = {
    "name": "Pat Testerson",
    "dob": "2030-01-01",
    "mrn": "SYN-000123",
}


def _draw_banner(c: canvas.Canvas, width: float, height: float) -> None:
    c.setFillColor(colors.HexColor("#B00020"))
    c.rect(0, height - 0.45 * inch, width, 0.45 * inch, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 10)
    c.drawCentredString(width / 2, height - 0.3 * inch, BANNER_TEXT)
    c.setFillColor(colors.black)


def _draw_field_block(c: canvas.Canvas, x: float, y: float, fields: dict[str, str]) -> float:
    c.setFont("Helvetica-Bold", 11)
    for label, value in fields.items():
        c.setFont("Helvetica-Bold", 10)
        c.drawString(x, y, f"{label}:")
        c.setFont("Helvetica", 10)
        c.drawString(x + 1.6 * inch, y, value)
        y -= 0.24 * inch
    return y


def make_referral_portal_pdf(path: Path) -> None:
    """Referral Portals: a structured web-form submission confirmation."""
    c = canvas.Canvas(str(path), pagesize=LETTER)
    width, height = LETTER
    _draw_banner(c, width, height)

    c.setFont("Helvetica-Bold", 16)
    c.drawString(1 * inch, height - 1 * inch, "Online Referral Portal \u2014 Submission Confirmation")
    c.setFont("Helvetica", 10)
    c.drawString(1 * inch, height - 1.25 * inch, "Portal: HomeCare Connect Referral Portal")
    c.drawString(1 * inch, height - 1.45 * inch, "Submission ID: PORTAL-SYN-90210")

    y = height - 1.9 * inch
    y = _draw_field_block(
        c,
        1 * inch,
        y,
        {
            "Patient": f"{PATIENT['name']} (synthetic)",
            "Date of birth": PATIENT["dob"],
            "MRN": PATIENT["mrn"],
            "Referral type": "Synthetic specialist consultation",
            "Priority": "Routine",
            "Service requested": "Synthetic care navigation",
            "Requested date": "2030-01-15",
        },
    )

    c.setFont("Helvetica-Bold", 10)
    c.drawString(1 * inch, y - 0.15 * inch, "Summary:")
    c.setFont("Helvetica", 10)
    c.drawString(
        1 * inch,
        y - 0.4 * inch,
        "Generated demonstration referral submitted via the self-service portal;",
    )
    c.drawString(1 * inch, y - 0.6 * inch, "contains no personal data.")

    c.setFont("Helvetica-Oblique", 8)
    c.drawString(1 * inch, 0.75 * inch, "Generated by samples/generate_samples.py for workshop use.")
    c.save()


def make_email_attachment_pdf(path: Path) -> None:
    """Email Attachments: a referral that arrived as an email attachment, printed with headers."""
    c = canvas.Canvas(str(path), pagesize=LETTER)
    width, height = LETTER
    _draw_banner(c, width, height)

    c.setFont("Helvetica-Bold", 14)
    c.drawString(1 * inch, height - 1 * inch, "Referral Attachment (received via email)")

    c.setFont("Helvetica-Bold", 9)
    header_y = height - 1.35 * inch
    headers = {
        "From": "referrals@synthetic-clinic.example",
        "To": "intake@homecare-referral.example",
        "Subject": "Referral: Synthetic specialist consultation",
        "Date": "Tue, 15 Jan 2030 09:14:00 -0600",
        "Attachment": "synthetic-email-attachment-referral.pdf",
    }
    for label, value in headers.items():
        c.setFont("Helvetica-Bold", 9)
        c.drawString(1 * inch, header_y, f"{label}:")
        c.setFont("Helvetica", 9)
        c.drawString(1.9 * inch, header_y, value)
        header_y -= 0.2 * inch

    c.line(1 * inch, header_y - 0.05 * inch, width - 1 * inch, header_y - 0.05 * inch)

    y = header_y - 0.4 * inch
    y = _draw_field_block(
        c,
        1 * inch,
        y,
        {
            "Patient": f"{PATIENT['name']} (synthetic)",
            "Date of birth": PATIENT["dob"],
            "MRN": PATIENT["mrn"],
            "Referral type": "Synthetic specialist consultation",
            "Priority": "Expedited",
            "Service requested": "Synthetic care navigation",
            "Requested date": "2030-01-20",
        },
    )

    c.setFont("Helvetica-Bold", 10)
    c.drawString(1 * inch, y - 0.15 * inch, "Summary:")
    c.setFont("Helvetica", 10)
    c.drawString(1 * inch, y - 0.4 * inch, "Generated demonstration referral forwarded as an email attachment;")
    c.drawString(1 * inch, y - 0.6 * inch, "contains no personal data.")

    c.setFont("Helvetica-Oblique", 8)
    c.drawString(1 * inch, 0.75 * inch, "Generated by samples/generate_samples.py for workshop use.")
    c.save()


def make_provider_referral_packet_pdf(path: Path) -> None:
    """Provider Referral Packets: a multi-page packet (cover letter + clinical summary)."""
    c = canvas.Canvas(str(path), pagesize=LETTER)
    width, height = LETTER

    # Page 1: referring-provider cover letter.
    _draw_banner(c, width, height)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(1 * inch, height - 1 * inch, "Springfield Family Medicine \u2014 Referral Cover Letter")
    c.setFont("Helvetica", 10)
    c.drawString(1 * inch, height - 1.3 * inch, "123 Synthetic Ave, Springfield, ST 00000")
    c.drawString(1 * inch, height - 1.48 * inch, "Referring provider: Dr. Sam Synthetica, MD (synthetic)")
    c.drawString(1 * inch, height - 1.66 * inch, "NPI: 0000000000 (synthetic, not a real identifier)")

    y = height - 2.1 * inch
    c.setFont("Helvetica", 10)
    for line in (
        "To the intake team,",
        "",
        "Please find enclosed a synthetic referral packet for the patient",
        "below. This packet is generated demonstration content only and",
        "does not describe a real person or real care episode.",
    ):
        c.drawString(1 * inch, y, line)
        y -= 0.22 * inch

    y -= 0.2 * inch
    y = _draw_field_block(
        c,
        1 * inch,
        y,
        {
            "Patient": f"{PATIENT['name']} (synthetic)",
            "Date of birth": PATIENT["dob"],
            "MRN": PATIENT["mrn"],
            "Referral type": "Synthetic specialist consultation",
            "Priority": "Routine",
            "Service requested": "Synthetic care navigation",
            "Requested date": "2030-02-01",
        },
    )
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(1 * inch, 0.75 * inch, "Page 1 of 2 \u2014 Generated by samples/generate_samples.py for workshop use.")
    c.showPage()

    # Page 2: clinical summary.
    _draw_banner(c, width, height)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(1 * inch, height - 1 * inch, "Clinical Summary (synthetic)")
    c.setFont("Helvetica", 10)
    y = height - 1.4 * inch
    for line in (
        "History: Synthetic placeholder history \u2014 no real clinical detail.",
        "Assessment: Synthetic placeholder assessment.",
        "Plan: Synthetic care navigation referral for demonstration purposes.",
        "",
        "Summary: Generated demonstration referral packet; contains no",
        "personal data.",
    ):
        c.drawString(1 * inch, y, line)
        y -= 0.24 * inch

    c.setFont("Helvetica-Oblique", 8)
    c.drawString(1 * inch, 0.75 * inch, "Page 2 of 2 \u2014 Generated by samples/generate_samples.py for workshop use.")
    c.save()


def make_external_partner_referral_pdf(path: Path) -> None:
    """External Healthcare Partners: referral from an outside health system's letterhead."""
    c = canvas.Canvas(str(path), pagesize=LETTER)
    width, height = LETTER
    _draw_banner(c, width, height)

    c.setFillColor(colors.HexColor("#1B3A6B"))
    c.setFont("Helvetica-Bold", 18)
    c.drawString(1 * inch, height - 1.05 * inch, "Partner Health Network")
    c.setFillColor(colors.black)
    c.setFont("Helvetica", 9)
    c.drawString(1 * inch, height - 1.25 * inch, "Interoperability Referral Exchange (synthetic partner organization)")
    c.line(1 * inch, height - 1.35 * inch, width - 1 * inch, height - 1.35 * inch)

    c.setFont("Helvetica-Bold", 13)
    c.drawString(1 * inch, height - 1.65 * inch, "Cross-Organization Referral Transmission")

    y = height - 2.05 * inch
    y = _draw_field_block(
        c,
        1 * inch,
        y,
        {
            "Sending organization": "Partner Health Network (synthetic)",
            "Receiving organization": "HomeCare Referral Intake (synthetic)",
            "Patient": f"{PATIENT['name']} (synthetic)",
            "Date of birth": PATIENT["dob"],
            "MRN": PATIENT["mrn"],
            "Referral type": "Synthetic specialist consultation",
            "Priority": "Routine",
            "Service requested": "Synthetic care navigation",
            "Requested date": "2030-02-10",
        },
    )

    c.setFont("Helvetica-Bold", 10)
    c.drawString(1 * inch, y - 0.15 * inch, "Summary:")
    c.setFont("Helvetica", 10)
    c.drawString(1 * inch, y - 0.4 * inch, "Generated demonstration referral received from an external partner")
    c.drawString(1 * inch, y - 0.6 * inch, "organization; contains no personal data.")

    c.setFont("Helvetica-Oblique", 8)
    c.drawString(1 * inch, 0.75 * inch, "Generated by samples/generate_samples.py for workshop use.")
    c.save()


def _load_font(size: int) -> ImageFont.FreeTypeFont:
    for candidate in (
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        "DejaVuSans.ttf",
    ):
        try:
            return ImageFont.truetype(candidate, size)
        except OSError:
            continue
    return ImageFont.load_default()


def _draw_image_banner(draw: ImageDraw.ImageDraw, width: int) -> None:
    draw.rectangle([(0, 0), (width, 40)], fill=(176, 0, 32))
    font = _load_font(14)
    draw.text((width / 2, 20), BANNER_TEXT, fill="white", anchor="mm", font=font)


def make_fax_coversheet_png(path: Path) -> None:
    """Fax Systems: a classic fax cover sheet transmission page."""
    width, height = 1275, 1650  # 8.5x11in @ 150dpi
    image = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(image)
    _draw_image_banner(draw, width)

    title_font = _load_font(30)
    label_font = _load_font(16)
    value_font = _load_font(16)
    small_font = _load_font(12)

    draw.text((80, 80), "FAX COVER SHEET", fill="black", font=title_font)
    draw.line([(80, 130), (width - 80, 130)], fill="black", width=2)

    fields = {
        "To": "HomeCare Referral Intake Fax Line \u2014 (000) 555-0102",
        "From": "Riverside Clinic Referrals Desk (synthetic)",
        "Fax number": "(000) 555-0199",
        "Date": "2030-01-18",
        "Pages": "2 (including this cover sheet)",
        "Re": "Synthetic specialist consultation referral",
    }
    y = 170
    for label, value in fields.items():
        draw.text((80, y), f"{label}:", fill="black", font=label_font)
        draw.text((320, y), value, fill="black", font=value_font)
        y += 40

    y += 20
    draw.line([(80, y), (width - 80, y)], fill="black", width=1)
    y += 30
    draw.text((80, y), "Patient details (synthetic):", fill="black", font=label_font)
    y += 40
    patient_fields = {
        "Patient": f"{PATIENT['name']} (synthetic)",
        "Date of birth": PATIENT["dob"],
        "MRN": PATIENT["mrn"],
        "Priority": "Expedited",
        "Requested date": "2030-01-22",
    }
    for label, value in patient_fields.items():
        draw.text((80, y), f"{label}:", fill="black", font=label_font)
        draw.text((320, y), value, fill="black", font=value_font)
        y += 36

    y += 30
    draw.text(
        (80, y),
        "Generated demonstration referral transmitted by fax; contains no personal data.",
        fill="black",
        font=small_font,
    )

    draw.text(
        (80, height - 60),
        "Generated by samples/generate_samples.py for workshop use.",
        fill=(90, 90, 90),
        font=small_font,
    )
    image.save(path, format="PNG")


def make_scanned_patient_chart_png(path: Path) -> None:
    """Scanned Patient Documents: a scanned intake-form-style chart page."""
    width, height = 1275, 1650
    image = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(image)
    _draw_image_banner(draw, width)

    title_font = _load_font(26)
    label_font = _load_font(16)
    value_font = _load_font(16)
    small_font = _load_font(12)

    draw.text((80, 80), "Patient Intake Chart (scanned copy)", fill="black", font=title_font)
    draw.rectangle([(80, 130), (width - 80, height - 120)], outline="black", width=2)

    y = 170
    for label, value in {
        "Patient": f"{PATIENT['name']} (synthetic)",
        "Date of birth": PATIENT["dob"],
        "MRN": PATIENT["mrn"],
        "Visit date": "2030-01-25",
    }.items():
        draw.text((110, y), f"{label}:", fill="black", font=label_font)
        draw.text((350, y), value, fill="black", font=value_font)
        y += 38

    y += 20
    draw.line([(110, y), (width - 110, y)], fill="black", width=1)
    y += 30
    draw.text((110, y), "Vitals (synthetic, placeholder values):", fill="black", font=label_font)
    y += 38
    for label, value in {
        "Blood pressure": "000/00 (placeholder)",
        "Heart rate": "00 bpm (placeholder)",
        "Temperature": "00.0 F (placeholder)",
    }.items():
        draw.text((110, y), f"{label}:", fill="black", font=label_font)
        draw.text((350, y), value, fill="black", font=value_font)
        y += 36

    y += 30
    draw.line([(110, y), (width - 110, y)], fill="black", width=1)
    y += 30
    draw.text((110, y), "Referral details:", fill="black", font=label_font)
    y += 38
    for label, value in {
        "Referral type": "Synthetic specialist consultation",
        "Priority": "Routine",
        "Service requested": "Synthetic care navigation",
        "Requested date": "2030-01-30",
    }.items():
        draw.text((110, y), f"{label}:", fill="black", font=label_font)
        draw.text((350, y), value, fill="black", font=value_font)
        y += 36

    y += 30
    draw.text(
        (110, y),
        "Generated demonstration chart page produced for workshop use; contains no personal data.",
        fill="black",
        font=small_font,
    )

    draw.text(
        (80, height - 60),
        "Generated by samples/generate_samples.py for workshop use.",
        fill=(90, 90, 90),
        font=small_font,
    )
    image.save(path, format="PNG")


def main() -> None:
    make_referral_portal_pdf(OUT_DIR / "synthetic-referral-portal-submission.pdf")
    make_fax_coversheet_png(OUT_DIR / "synthetic-fax-referral-coversheet.png")
    make_email_attachment_pdf(OUT_DIR / "synthetic-email-attachment-referral.pdf")
    make_scanned_patient_chart_png(OUT_DIR / "synthetic-scanned-patient-chart.png")
    make_provider_referral_packet_pdf(OUT_DIR / "synthetic-provider-referral-packet.pdf")
    make_external_partner_referral_pdf(OUT_DIR / "synthetic-external-partner-referral.pdf")
    print("Generated 6 synthetic sample documents in", OUT_DIR)


if __name__ == "__main__":
    main()
